=== PhoneJ2ME/releases/phoneme_feature-mr1-rel-b04/jsr135/win32-jsr135/src/config/configuration.dtd
<!--

  Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER

-->
<!ELEMENT configuration (properties | constants)+>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>
<!ELEMENT constants (constant_class)+>
<!ELEMENT constant_class (constant)+>
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type     (int | String | boolean)       #IMPLIED
    Name     CDATA                          #REQUIRED
    Value    CDATA                          #REQUIRED
    VScope   (protected | public | private) #REQUIRED
    Comment  CDATA                          #IMPLIED
>

=== PhoneJ2ME/releases/phoneme_feature-mr2-rel-b23/jsr177/src/config/common/i18n_constants_jsr177.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
      

    Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
    
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License version
    2 only, as published by the Free Software Foundation.
    
    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    General Public License version 2 for more details (a copy is
    included at /legal/license.txt).
    
    You should have received a copy of the GNU General Public License
    version 2 along with this work; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
    02110-1301 USA
    
    Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
    Clara, CA 95054 or visit www.sun.com if you need additional
    information or have any questions.
-->
<configuration>
<constants>
<!-- i18n Resource constants -->
<constant_class Package="com.sun.midp.i18n" Name="ResourceConstants" Scope="public"
    AutoValue="true" JavaOnly="true" KeysValuesProvider="true" >

     <constant Type="int"
        Name="JSR177_WIM_NOT_FOUND"
        Comment="SATSA: com.sun.satsa.pki.PKIManager"/>
            
    <constant Type="int"
        Name="JSR177_CONFIRM_SIGNATURE"
        Comment="SATSA: com.sun.satsa.pki.PKIManager"/>
            
    <constant Type="int"
        Name="JSR177_STRING_TO_SIGN"
        Comment="SATSA: com.sun.satsa.pki.PKIManager"/>
            
    <constant Type="int"
        Name="JSR177_WIM_PIN_BLOCKED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_WIM_PIN_NOT_VERIFIED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_CERTIFICATE_USED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_SELECT_CERTIFICATE"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_CERTIFICATES_AVAILABLE"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_CERTIFICATE_GENERATED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_CERTIFICATE_STORED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>
            
    <constant Type="int"
        Name="JSR177_CERTIFICATE_DELETED"
        Comment="SATSA: com.sun.satsa.pki.WIMApplication"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_SUBJECT"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_KEYUSAGE"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_KEYUSAGE_AUTH"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_KEYUSAGE_NR"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_ALGORITHM"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_KEYLENGTH"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_LABEL"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_ISSUER"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_SN"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_VALIDFROM"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_CERTIFICATE_VALIDTILL"
        Comment="SATSA: com.sun.satsa.pki.Certificate"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_NEWPIN"
        Comment="SATSA: com.sun.satsa.pki.MessageDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_LABEL"
        Comment="SATSA: com.sun.satsa.pki.MessageDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_ENTERPIN"
        Comment="SATSA: com.sun.satsa.pki.MessageDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_CONFIRMPIN"
        Comment="SATSA: com.sun.satsa.pki.MessageDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_VERIFY"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_CHANGE"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_DISABLE"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_ENABLE"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_TITLE_UNBLOCK"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

    <constant Type="int"
        Name="JSR177_PINDIALOG_NEWVALUE"
        Comment="SATSA: com.sun.satsa.acl.PINDialog"/>

</constant_class>
</constants>
</configuration>

=== PhoneJ2ME/releases/phoneme_feature-mr1-rc-b04/jsr120/src/config/common/properties_jsr120.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
  
  Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
-->
<!-- System-independent JSR 205 properties required by the specification -->
<configuration>
  <properties>
    <!-- SYSTEM PROPERTIES -->
    <!-- Visible from System.getProperty() -->

    <property Key="wireless.messaging.version"
      Value="1.1"
      Scope="system"
      Comment="WMA version number."/>

    <property Key="wireless.messaging.sms.smsc"
      Value="+17815511212"
      Scope="system"
      Comment="Default SMS Service Center address."/>
    
    <!-- INTERNAL PROPERTIES -->
    <!-- Visible from Configuration.getProperty() -->
    <property Key="com.sun.midp.io.j2me.wma.DatagramHost"
      Value="wmadatagramhost"
      Comment="The datagram host name for wma emulated messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortIn"
      Value="11100"
      Scope="internal"
      Comment="The datagram port number for inbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortOut"
      Value="11101"
      Scope="internal"
      Comment="The datagram port number of outbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.cbs.DatagramPortIn"
      Value="22200"
      Scope="internal"
      Comment="The datagram port number for inbound CBS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.PhoneNumber"
      Value="+5551212"
      Scope="internal"
      Comment="The phone number for outbound messages from the SMS emulator."/>
    
  </properties>
</configuration>

=== PhoneJ2ME/releases/phoneme_feature-mr1-rel-b04/jsr177/src/config/common/properties_jsr177.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
    @(#)properties_jsr177.xml	1.12 06/04/26 @(#)

    Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
-->

<configuration>
<properties>
    <property Key="microedition.smartcardslots"
        Value="0C,1H"
        Scope="system"
        Comment="Smart card slot identifiers."/>

    <property Key="com.sun.midp.io.j2me.apdu.satselectapdu"
        Value="00.a4.04.00.07.a0.00.00.00.62.3.1.7F"
        Scope="internal"
        Comment="APDU command for selecting SIM application."/>

    <property Key="com.sun.satsa.store_csr_list"
        Value="true"
        Scope="internal"
        Comment="Save persistent copy of CSR public keys."/>

    <property Key="com.sun.satsa.keygen"
        Value="true"
        Scope="internal"
        Comment="Internal flag to identify key generation."/>

    <property Key="com.sun.satsa.certsig"
        Value="true"
        Scope="internal"
        Comment="Internal flag to identify certificate signing."/>

    <property Key="microedition.satsa.crypto.version"
        Value="1.0"
        Scope="system"
        Comment="Version of SATSA-CRYPTO API supported by the device."/>

    <property Key="microedition.satsa.apdu.version"
        Value="1.0"
        Scope="system"
        Comment="Version of SATSA-APDU API supported by the device."/>

    <property Key="microedition.satsa.pki.version"
        Value="1.0"
        Scope="system"
        Comment="Version of SATSA-PKI API supported by the device."/>

</properties>
</configuration>

=== PhoneJ2ME/releases/phoneme_feature-mr1-rel-b04/midp/src/configuration/configuration_xml/linux_qte/platform_alert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../share/configuration.dtd">
<!--
        @(#)platform_alert.xml	1.2	06/04/05

        Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This source file is specific for Qt-based configurations.
-->
<configuration>
<constants>
<constant_class Package="com.sun.midp.configurator" Name="Constants" Scope="public">
<!-- Package javax.microedition.lcdui -->
  <constant Type="int"
	    Name="ALERT_NUM_OF_BUTTONS"
	    Value="3"
	    Comment="Number of buttons for abstract commands."/>
  <constant Type="int"
	    Name="ALERT_BUTTON_WIDTH"
	    Value="40"
	    Comment="Width of an abstract command."/>
  <constant Type="int"
	    Name="ALERT_BUTTON_HEIGHT"
	    Value="20"
	    Comment="Height of an abstract command."/>
  <constant Type="int"
	    Name="ALERT_CELL_SPACING"
	    Value="4"
	    Comment="Space between image, text and buttons."/>
  <constant Type="int"
	    Name="ALERT_WIDTH"
	    Value="140"
	    Comment="Width of the alert dialog window."/>
  <constant Type="int"
	    Name="ALERT_HEIGHT"
	    Value="120"
	    Comment="Height of the alert dialog window."/>
 </constant_class>
</constants>
</configuration>

=== PhoneJ2ME/releases/phoneme_feature-mr1-rc-b04/jsr135/linux-abb/src/config/properties.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
  
  Copyright 1990-2006 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
-->
<!-- System-independent JSR 234 properties required by the specification -->
<configuration>
  <properties>
    <!-- SYSTEM PROPERTIES -->
    <!-- Visible from System.getProperty() -->

    <!-- JSR135(MMAPI) PROPERTIES -->
    <property Key="microedition.media.version"
      Value="1.1"
      Scope="system"
      Comment="Version number."/>

    <property Key="mmapi-configuration"
      Value="com.sun.mmedia.CougarQSoundAbbConfig"
      Scope="system"
      Comment="Type of configuration."/>

    <property Key="supports.mixing"
      Value="true"
      Scope="system"
      Comment="Mixing support."/>

    <property Key="supports.audio.capture"
      Value="false"
      Scope="system"
      Comment="Audio capture support."/>

    <property Key="supports.video.capture"
      Value="false"
      Scope="system"
      Comment="Video capture support."/>

    <property Key="supports.recording"
      Value="true"
      Scope="system"
      Comment="Recording support."/>
    
    <!--
    <property Key="audio.encodings"
      Value="encoding=pcm encoding=pcm&amp;rate=8000&amp;bits=8&amp;channels=1 encoding=pcm&amp;rate=22050&amp;bits=16&amp;channels=2"
      Scope="system"
      Comment="Supported audio encodings."/>
    -->

    <!--
    <property Key="video.encodings"
      Value="encoding=rgb565&amp;width=160&amp;height=120 encoding=rgb565&amp;width=320&amp;height=240 encoding=rgb565&amp;width=120&amp;height=160"
      Scope="system"
      Comment="Supported video encodings."/>
    -->

    <property Key="video.snapshot.encodings"
      Value="encoding=jpeg encoding=png"
      Scope="system"
      Comment="Supported video snapshot encodings."/>

    <property Key="streamable.contents"
      Value="audio/x-wav"
      Scope="system"
      Comment="Streamable contents."/>

    <!-- JSR234(AMMS) PROPERTIES -->
    <!--
    <property Key="microedition.amms.version"
      Value="1.0"
      Scope="system"
      Comment="Advanced Multimedia Supplements version number."/>
    -->

    <!--
    <property Key="supports.mediacapabilities" 
      Value="imageencoding imagepostprocessing"
      Scope="system"
      Comment="Supported AMMS media capabilities"/>
    -->

    <!--
    <property Key="audio.samplerates" 
      Value="44100 22050"
      Scope="system"
      Comment="Recommended audio sample rates"/>
    -->

    <!--
    <property Key="audio3d.simultaneouslocations" 
      Value="0"
      Scope="system"
      Comment="Maximum number of simultaneously supported SoundSource3D instances"/>
    -->

    <!--
    <property Key="tuner.modulations" 
      Value=""
      Scope="system"
      Comment="Supported tuner modulation settings"/>
    -->

    <!--
    <property Key="camera.resolutions" 
      Value=""
      Scope="system"
      Comment="Specifies the sensor sizes of the cameras of the device"/>
    -->

    <!--
    <property Key="camera.orientations" 
      Value=""
      Scope="system"
      Comment="Specifies the orientations of the cameras of the device"/>
    -->

    <!-- INTERNAL PROPERTIES -->
    <!-- Visible from Configuration.getProperty() -->
    
  </properties>
</configuration>
